### ISSUE TITLE
string vs bytes type error

### ISSUE THREAD

**Issue by jason-ford-silicontx** [mtzgroup/tcpb-client#24]
Hi, I'm getting the following (truncated) error, seemingly at random, although only on certain nodes. I'm using TeraChem compiled on May 28th, 2021 and tcpb 0.8.0. 

```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:577] String field 'terachem_server.JobOutput.orb1afile' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
Traceback (most recent call last):
  File "/projects2/common/SOFTWARE/miniconda3/envs/apps3/lib/python3.7/site-packages/tcpb/tcpb.py", line 466, in compute_job_sync
    return self.recv_job_async()
  File "/projects2/common/SOFTWARE/miniconda3/envs/apps3/lib/python3.7/site-packages/tcpb/tcpb.py", line 322, in recv_job_async
    output = self._recv_msg(pb.JOBOUTPUT)
  File "/projects2/common/SOFTWARE/miniconda3/envs/apps3/lib/python3.7/site-packages/tcpb/tcpb.py", line 845, in _recv_msg
    recv_pb.ParseFromString(msg_str)
google.protobuf.message.DecodeError: Error parsing message
```

I made the recommended change in the tcpb-client proto file from `string` to `bytes` and noticed that the `result['orbfile']` contains garbage bytes, which cause another error if you try to decode them. For example, most of the time we get something like this:
```
b'server_2021-06-11-12.44.40/job_1/scr/c0'
```
but occasionally/seemingly randomly get three extra "characters"
```
b'server_2021-06-11-12.25.21/job_1/scr/c0\xee\xfc\x7f'
```
which cannot be decoded into UTF-8 in python and raise a different error.

For now we've hacked it to strip off the garbage bytes prior to decoding, but this likely needs to be fixed on the terachem side.

**Comment by coltonbh** [comment]
@jason-ford-silicontx thanks for the sleuthing!

I believe the latest build of TeraChem is not passing all `tcpb` tests. @henryw7 can you confirm? And is Jason's issue related to the current state of TeraChem's TCPB server with the failed tests?

**Comment by henryw7** [comment]
Hi, I'm not sure of either TeraChem version or tcpb version you're talking about, but that seems like a protobuf version problem. Try `rm commbox/src/terachem_server.pb.*` in terachem repo and rm the `terachem_server_pb2.py` (wherever that is) in tcpb repo, generate them using the same version of `protoc`.
What Colton is talking about is that the tip version of TeraChem doesn't pass the benzene-PCM, any IMD, and any ci-overlap tests in tcautotest. A TeraChem version from last year is save in this aspect.

**Comment by jason-ford-silicontx** [comment]
Thanks guys for responding so quickly. It could very well be a protobuf version problem; I only have the precompiled binary so I'm not sure what version of protobuf or pb file was actually used for the compilation. I have libprotobuf.so.25, so if you know what the pb file should look like for that then I would love to test it and get away from my current hack. I think I was seeing similar behavior with the tests, but assumed it was less important numerical issues.

**Comment by coltonbh** [comment]
It's easy for me to respond quickly and say @henryw7 what do you think??! 😂

Sorry I can't be more helpful. Looking forward to the days when I've gotten more into the TC internals and will know how to tackle these issues from first principles. Keep me posted on what you figure out on this thread though--will be a good record to have for future debugging :)

**Comment by henryw7** [comment]
libprotobuf.so.25 probably corresponds to `protobuf/3.14.0`.
For the autotest, I've tested on a 2021/05 version of terachem, and for benzene+PCM case the result is far beyond numerical error range, and IMD and ci_overlap tests just induce seg fault / python error. Maybe it's better with older terachem version. Just be a bit careful. I'll try to fix these after Scott's effort to remove globals in terachem.

**Comment by henryw7** [comment]
I'll response as soon as I look at my gmail :)

**Comment by jason-ford-silicontx** [comment]
Hahah well I'm glad Henry looks at his gmail so frequently then 😁 Thanks Henry, I'll try recompiling the proto code with `3.14.0` and will get back to you if I find anything useful.

**Comment by jason-ford-silicontx** [comment]
Hi guys, sorry for the slow response. As an update, I found a similar error in the optim.pdb generated during an optimization calculation, not involving TCPB at all, so I assume the issue is somewhere in TeraChem proper, probably in C-string handling somewhere due to the erratic behavior. I can't post the whole structure due to IP reasons, but here is the top of the input coordinate file:
![image](https://user-images.githubusercontent.com/81584643/122773081-a49db800-d26d-11eb-94b5-7cee7709f447.png)
and the optim.pdb file (as rendered by vim):
![image](https://user-images.githubusercontent.com/81584643/122773132-b1221080-d26d-11eb-8f82-cd1db83be56c.png)
As you can see, the carbon and nitrogen atom names have a few "garbage" bytes after the name. This is all to say that I don't think it's a TCPB error I'm seeing, and thanks for any time you spent looking into it. We have workarounds for now, but I would appreciate if either of you let me know if you see any updates to TeraChem that might fix the garbage byte writing that I've seen.

**Comment by coltonbh** [comment]
Thanks for the followup!

**Comment by henryw7** [comment]
@jason-ford-silicontx I have some clue where the bug is in TeraChem. Would you mind send us a terachem input file you're using to trigger that pdb output bug, and a input pdb geometry if possible?
