### ISSUE TITLE
for loop over cis_transition_dipole requires integer as an argument

### ISSUE THREAD

**Issue by ChristopherAMyers** [mtzgroup/tcpb-client#39]
This is a small issue in `clients.py:recv_job_async`

```
  File "/XXXXXXX/tcpb-client/tcpb/clients.py", line 518, in recv_job_async
    for i in range((output.cis_states + 1) * output.cis_states / 2):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
```
wrapping the expression in `range` fixes the issue:
`for i in range(int((output.cis_states + 1) * output.cis_states / 2)):`

**Comment by tmartine68** [comment]
sounds like a python 3 vs python 2 thing.  but your fix should work also in python 2.7, so go ahead and issue a pull request.

**Comment by tmartine68** [comment]
Should be resolved.

**Comment by coltonbh** [comment]
Thanks @ChristopherAMyers for the quick fix. I've released a new version of the client including your patch to PyPi (v0.13.2). You can install it with `pip install tcpb` or if you're installing into an environment that already has `tcpb` then `pip install --upgrade tcpb` to get the latest version. 

@tmartine68 just a heads up that this package does not support python 2.7. 2.7 reach end of life at the end of 2019 and I dropped support a few years back.
