### ISSUE TITLE
Request to remove the print line of "Checking jobs status..." in `check_job_complete()`

### ISSUE THREAD

**Issue by rywang42** [mtzgroup/tcpb-client#44]
Hi, I'm porting nanoreactor from python2.7 to python3, which now does no longer need to use the tcpb for python2.7. However, I noticed that every call of `check_job_complete()` will print out a line of "Checking jobs status..." which cannot be turned off, and very much disturbs nanoreactor's log file, making it difficult to locate the really significant outputs among debugging lines. It could be great if Colton (or other developers) can help remove that line, or setting it to a debug logging level. Thanks in advance! 
(I tried to open a pull request but I seemed to have no permission to access the remote of this repo.)

Ruiyan

**Comment by rywang42** [comment]
Sorry that for now I think I could also just post-process the nanoreactor logs...

**Comment by coltonbh** [comment]
Hi @rywang42. Happy to remove superfluous logging messages! Agree they were not helpful. If you fork the repo and then open a PR that solves your issue I'd be happy to review, merge to master, and publish a new release :) You will not need to push to the remote of this repo. Simply use your forked repo and then open a PR against this one.

Let me know if you have any questions on the implementation!
